id: P755AEF0E
initial_creation_type: ocr
source_metadata:
  volumes:
    791e7b9ddcf94e748a010662bc2dc99d:
      base_file: v064.txt
      image_group_id: I1PD95909
      title: རྣལ་འབྱོར་གསུམ་པ་ལ་འཇུག་པ།
      total_pages: 1902
      volume_number: 64
